//
// Created by max on 12.04.21.
//

#ifndef MIRA3D_REACHABILITY_VISUALIZE_WORKSPACE_H
#define MIRA3D_REACHABILITY_VISUALIZE_WORKSPACE_H


class visualize_workspace {

};


#endif //MIRA3D_REACHABILITY_VISUALIZE_WORKSPACE_H
